language: julia

os:
    - linux

julia:
    - 1.2

env:
    - PYTHON=""

notifications:
  email: false

jobs:
  include:
      - stage: "Testing"
        julia: 1.2
        os: linux
        script:
            - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(;coverage=true)';
        after_success: skip
#           - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());';
      - stage: "Documentation"
        julia: 1.2
        os: linux
        script:
          - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();';
          - julia --project=docs/ docs/make.jl
        after_success: skip
