language: julia

os:
    - linux

julia:
    - 1.0

env:
    - PYTHON=""

notifications:
  email: false

jobs:
  include:
      - stage: "Testing"
        julia: 1.0
        os: linux
        script:
<<<<<<< HEAD
            - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';
        after_success: skip
       #    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());';
=======
            - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(;coverage=true)';
        after_success: skip
#           - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder());';
>>>>>>> constrained_newAPI
      - stage: "Documentation"
        julia: 1.0
        os: linux
        script:
          - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate();';
          - travis_wait 30 julia --project=docs/ docs/make.jl
        after_success: skip
