name = "spike_data_latent_accum"
uuid = "c2542da2-1f7d-11e9-2506-87691095ebb2"
authors = ["Brian DePasquale <depasquale@princeton.edu>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
