name = "pulse_input_DDM.jl"
uuid = "c2542da2-1f7d-11e9-2506-87691095ebb2"
authors = ["Brian DePasquale <depasquale@princeton.edu>"]
version = "0.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
